/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-comm_tools
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_COMM_TOOLS_API_H
#define INCLUDED_COMM_TOOLS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_comm_tools_EXPORTS
#define COMM_TOOLS_API __GR_ATTR_EXPORT
#else
#define COMM_TOOLS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_COMM_TOOLS_API_H */
