/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bpsk_phase_ambiguity_solver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a8e774dcba54a183eef62fdff2d38bb8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/comm_tools/bpsk_phase_ambiguity_solver.h>
// pydoc.h is automatically generated in the build directory
#include <bpsk_phase_ambiguity_solver_pydoc.h>

void bind_bpsk_phase_ambiguity_solver(py::module& m)
{

    using bpsk_phase_ambiguity_solver    = gr::comm_tools::bpsk_phase_ambiguity_solver;


    py::class_<bpsk_phase_ambiguity_solver, gr::sync_block,
        std::shared_ptr<bpsk_phase_ambiguity_solver>>(m, "bpsk_phase_ambiguity_solver", D(bpsk_phase_ambiguity_solver))

        .def(py::init(&bpsk_phase_ambiguity_solver::make),
           py::arg("sync_word"),
           py::arg("tolerance"),
           py::arg("tag_lock_name"),
           D(bpsk_phase_ambiguity_solver,make)
        )
        
        .def("set_sync_word", &bpsk_phase_ambiguity_solver::set_sync_word, py::arg("sync_word"), D(bpsk_phase_ambiguity_solver, set_sync_word))  
        .def("set_tolerance", &bpsk_phase_ambiguity_solver::set_tolerance, py::arg("tolerance"), D(bpsk_phase_ambiguity_solver, set_tolerance))  

        ;




}








