/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(latch_selector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(348d19f89001d41a848125a87f5c7229)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/comm_tools/latch_selector.h>
// pydoc.h is automatically generated in the build directory
#include <latch_selector_pydoc.h>

void bind_latch_selector(py::module& m)
{

    using latch_selector    = gr::comm_tools::latch_selector;


    py::class_<latch_selector, gr::block, gr::basic_block,
        std::shared_ptr<latch_selector>>(m, "latch_selector", D(latch_selector))

        .def(py::init(&latch_selector::make),
           py::arg("itemsize"),
           py::arg("set_key"),
           py::arg("reset_key"),
           py::arg("toggle_key"),
           D(latch_selector,make)
        )
        
        .def("set_set_key",&latch_selector::set_set_key,       
            py::arg("set_key"),
            D(latch_selector,set_set_key)
        )


        
        .def("set_reset_key",&latch_selector::set_reset_key,       
            py::arg("reset_key"),
            D(latch_selector,set_reset_key)
        )
        
        
        .def("set_toggle_key",&latch_selector::set_toggle_key,       
            py::arg("toggle_key"),
            D(latch_selector,set_toggle_key)
        )
        
        ;




}








