/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(threshold_tag.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a9b31915ed9245300658c80937c039a7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/comm_tools/threshold_tag.h>
// pydoc.h is automatically generated in the build directory
#include <threshold_tag_pydoc.h>

void bind_threshold_tag(py::module& m)
{

    using threshold_tag    = gr::comm_tools::threshold_tag;


    py::class_<threshold_tag, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<threshold_tag>>(m, "threshold_tag", D(threshold_tag))

        .def(py::init(&threshold_tag::make),
           py::arg("lo"),
           py::arg("hi"),
           py::arg("high_key"),
           py::arg("low_key"),
           py::arg("en_high"),
           py::arg("en_low"),
           py::arg("initial_state") =  0,
           D(threshold_tag,make)
        )
        
        .def("set_hi",&threshold_tag::set_hi,       
            py::arg("hi"),
            D(threshold_tag,set_hi)
        )


        
        .def("set_lo",&threshold_tag::set_lo,       
            py::arg("lo"),
            D(threshold_tag,set_lo)
        )


        ;




}








